### ISSUE TITLE
missing @AdminPresentationMap annotation on SkuImpl.fulfillmentFlatRates

### ISSUE THREAD

**Issue by letshan** [BroadleafCommerce/BroadleafCommerce#1122]
SkuImpl.fulfillmentFlatRates: this field should be able to expose to the admin function to be configurable. 

At the moment it's missing the annotation and couldn't be seen on shipping tab (or any other tabs for Sku)

**Comment by cja769** [comment]
Caused by: java.lang.IllegalArgumentException: Key class for AdminPresentationMap was determined to be a JPA managed type. Only primitive types for the key type are currently supported.
	at org.broadleafcommerce.openadmin.server.dao.provider.metadata.MapFieldMetadataProvider.buildMapMetadata(MapFieldMetadataProvider.java:478)
	at org.broadleafcommerce.openadmin.server.dao.provider.metadata.MapFieldMetadataProvider.addMetadata(MapFieldMetadataProvider.java:87)
	at org.broadleafcommerce.openadmin.server.dao.Metadata.getFieldPresentationAttributes(Metadata.java:69)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.getPropertiesForEntityClass(DynamicEntityDaoImpl.java:803)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.buildPropertiesFromPolymorphicEntities(DynamicEntityDaoImpl.java:652)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl$1.execute(DynamicEntityDaoImpl.java:497)
	at org.broadleafcommerce.openadmin.server.dao.Metadata.overrideMetadata(Metadata.java:97)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.getMergedPropertiesRecursively(DynamicEntityDaoImpl.java:518)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.buildEntityProperties(DynamicEntityDaoImpl.java:1189)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.buildBasicProperty(DynamicEntityDaoImpl.java:1115)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.buildProperties(DynamicEntityDaoImpl.java:968)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.getPropertiesForEntityClass(DynamicEntityDaoImpl.java:833)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.buildPropertiesFromPolymorphicEntities(DynamicEntityDaoImpl.java:652)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl$1.execute(DynamicEntityDaoImpl.java:497)
	at org.broadleafcommerce.openadmin.server.dao.Metadata.overrideMetadata(Metadata.java:97)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.getMergedPropertiesRecursively(DynamicEntityDaoImpl.java:518)
	at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.getMergedProperties(DynamicEntityDaoImpl.java:416)
	at org.broadleafcommerce.openadmin.server.service.persistence.module.BasicPersistenceModule.updateMergedProperties(BasicPersistenceModule.java:890)
	at org.broadleafcommerce.openadmin.server.service.persistence.PersistenceManagerImpl.inspect(PersistenceManagerImpl.java:248)
	at org.broadleafcommerce.openadmin.server.service.DynamicEntityRemoteService$1.execute(DynamicEntityRemoteService.java:96)
	... 127 more

**Comment by cja769** [comment]
This is the code that was added which produced the aforementioned error:

    @AdminPresentationMap(friendlyName = "SkuImpl_Sku_Fulfillment_Flat_Rates",
        tab = Presentation.Tab.Name.Shipping, tabOrder = Presentation.Tab.Order.Shipping,
        forceFreeFormKeys = true )
