### ISSUE TITLE
i18n Enhancement: certain fields on some entities should be translatable. (e.g. Attributes/Challenge Question)

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#1226]
Certain fields on the following entities should be translatable:

- [x] ChallengeQuestion.getQuestion()
- [x] SkuAttribute.getName()
- [x] SkuAttribute.getValue()
- [x] ProductAttribute.getName()
- [x] ProductAttribute.getValue()
- [x] CategoryAttribute.getName()
- [x] CategoryAttribute.getValue()
- [x] CustomerAttribute.getName()
- [x] CustomerAttribute.getValue()

Also make sure the entities are configured in the `org.broadleafcommerce.common.i18n.domain.TranslatedEntity` enum.

As well as increase the maxElements for the default `blTranslationElements` region in the ehcache config to be `100000` to at least match the region for categories and products

**Comment by phillipuniverse** [comment]
@jefffischer I think this is the issue that is causing problems for you. It looks like some of the referenced entities for translations are not actually in any applicationContext-entity.xml such as:

- CustomerAttribute
- ProductAttribute
- SkuAttribute
- CustomerAttribute

For the issue that you had with bean mapping, if any of those bean mappers invoked these methods then they would fail.

I discovered this on startup with heat clinic on 3.1 I got this when it tried to build the index:

```console
[artifact:mvn] [TRACE] 18:50:15 SolrIndexServiceImpl - Could not get value for property[product.productAttributes.heatRange] for product id[11]
[artifact:mvn] java.lang.reflect.InvocationTargetException
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:1773)
[artifact:mvn] 	at org.apache.commons.beanutils.PropertyUtilsBean.getSimpleProperty(PropertyUtilsBean.java:1132)
[artifact:mvn] 	at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:686)
[artifact:mvn] 	at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:715)
[artifact:mvn] 	at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:290)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.getPropertyValues(SolrIndexServiceImpl.java:512)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.buildDocument(SolrIndexServiceImpl.java:380)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.buildIncrementalIndex(SolrIndexServiceImpl.java:277)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.buildIncrementalIndex(SolrIndexServiceImpl.java:238)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl$1.execute(SolrIndexServiceImpl.java:187)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.performCachedOperation(SolrIndexServiceImpl.java:124)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexServiceImpl.rebuildIndex(SolrIndexServiceImpl.java:181)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrSearchServiceImpl.rebuildIndex(SolrSearchServiceImpl.java:264)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
[artifact:mvn] 	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
[artifact:mvn] 	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
[artifact:mvn] 	at org.quartz.core.JobRunShell.run(JobRunShell.java:207)
[artifact:mvn] 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:560)
[artifact:mvn] Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.broadleafcommerce.core.catalog.domain.ProductAttribute' is defined
[artifact:mvn] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:575)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1111)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276)
```

**Comment by phillipuniverse** [comment]
@jefffischer I'm making the fixes here I'll push up when I'm done.

**Comment by akdasari** [comment]
I'm still having the above problem, did u guys fixed this
[ERROR] 22:14:40 SolrIndexServiceImpl - Could not get value for property[product.productAttributes.heatRange] for product id[1]
