### ISSUE TITLE
Adding a map collection to a subclass of ProductImpl causes an exception when viewing ProductBundles

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1265]
In `AdminEntityServiceImpl`getRecordsForAllSubCollections` does not attempt to filter out properties that are not actually applicable to the current entity. The exception that happens is:

```console
[artifact:mvn] Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[artifact:mvn]  at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[artifact:mvn]  at java.util.ArrayList.get(ArrayList.java:429)
[artifact:mvn]  at org.broadleafcommerce.openadmin.server.service.persistence.module.MapStructurePersistenceModule.fetch(MapStructurePersistenceModule.java:517)
[artifact:mvn]  at org.broadleafcommerce.openadmin.server.service.persistence.PersistenceManagerImpl.fetch(PersistenceManagerImpl.java:298)
[artifact:mvn]  at com.broadleafcommerce.tenant.service.MultiTenantPersistenceManagerImpl.fetch(MultiTenantPersistenceManagerImpl.java:62)
[artifact:mvn]  at org.broadleafcommerce.openadmin.server.service.DynamicEntityRemoteService$2.execute(DynamicEntityRemoteService.java:108)
```

**Comment by phillipuniverse** [comment]
That said, this is theoretically also happening for other subcollections too there just isn't an exception. If you go and view a `ProductImpl` then in the list of properties that come back `skuBundleItems` is included. There is still a request that goes out to retrieve `SkuBundleItems` but it just comes back with an empty result set.

These lookups should be filtered out according to the type.
