### ISSUE TITLE
Admin minification of javascript doesn't work anymore

### ISSUE THREAD

**Issue by Pr0TuX** [BroadleafCommerce/BroadleafCommerce#1284]
**Broadleaf Framework** : 3.1.12-GA
**Admin demo project** : 3.1.12-GA

**Steps to reproduce**

1.) Go to admin
2.) Login

**Expected result** :  Admin javascript should be minified
**Actual result** :  Admin javascript adminlib.js isn't minified.

It doens't reproduce into : 3.1.8-GA, only into 3.1.9+. I suspect that after redactoring was upgraded or refactored this problem occurs.

It might be because of this ticket #1152 
Also log is full of this stack trace : 

```
2015-03-09 18:50:51,215 | ERROR | ResourceMinificationServiceImpl: 23402invalid return
2015-03-09 18:50:51,216 | ERROR | ResourceMinificationServiceImpl: 23407invalid return
2015-03-09 18:50:51,216 | ERROR | ResourceMinificationServiceImpl: 23409invalid return
2015-03-09 18:50:51,216 | ERROR | ResourceMinificationServiceImpl: 23403syntax error
2015-03-09 18:50:51,216 | ERROR | ResourceMinificationServiceImpl: 23422syntax error
2015-03-09 18:50:51,217 | ERROR | ResourceMinificationServiceImpl: 23428invalid return
2015-03-09 18:50:51,217 | ERROR | ResourceMinificationServiceImpl: 23432invalid return
2015-03-09 18:50:51,217 | ERROR | ResourceMinificationServiceImpl: 23426syntax error
2015-03-09 18:50:51,217 | ERROR | ResourceMinificationServiceImpl: 23448syntax error
2015-03-09 18:50:51,218 | ERROR | ResourceMinificationServiceImpl: 23436invalid return
2015-03-09 18:50:51,218 | ERROR | ResourceMinificationServiceImpl: 23430syntax error
2015-03-09 18:50:51,218 | ERROR | ResourceMinificationServiceImpl: 23442syntax error
2015-03-09 18:50:51,218 | ERROR | ResourceMinificationServiceImpl: 23443invalid return
2015-03-09 18:50:51,218 | ERROR | ResourceMinificationServiceImpl: 23437syntax error
2015-03-09 18:50:51,219 | ERROR | ResourceMinificationServiceImpl: 23449syntax error
2015-03-09 18:50:51,219 | ERROR | ResourceMinificationServiceImpl: 23447invalid return
2015-03-09 18:50:51,219 | ERROR | ResourceMinificationServiceImpl: 23441syntax error
2015-03-09 18:50:51,219 | ERROR | ResourceMinificationServiceImpl: 23449syntax error
2015-03-09 18:50:51,220 | ERROR | ResourceMinificationServiceImpl: 23451invalid return
2015-03-09 18:50:51,220 | ERROR | ResourceMinificationServiceImpl: 23445syntax error
2015-03-09 18:50:51,220 | ERROR | ResourceMinificationServiceImpl: 23454syntax error
2015-03-09 18:50:51,261 | ERROR | ResourceMinificationServiceImpl: 23492invalid return
2015-03-09 18:50:51,261 | ERROR | ResourceMinificationServiceImpl: 23492invalid return
2015-03-09 18:50:51,261 | ERROR | ResourceMinificationServiceImpl: 23490invalid return
2015-03-09 18:50:51,261 | ERROR | ResourceMinificationServiceImpl: 23492invalid return
2015-03-09 18:50:51,261 | ERROR | ResourceMinificationServiceImpl: 23471invalid return
2015-03-09 18:50:51,262 | ERROR | ResourceMinificationServiceImpl: 23465syntax error
2015-03-09 18:50:51,262 | ERROR | ResourceMinificationServiceImpl: 23465syntax error
2015-03-09 18:50:51,262 | ERROR | ResourceMinificationServiceImpl: 23550syntax error
2015-03-09 18:50:51,279 | ERROR | ResourceMinificationServiceImpl: 117Compilation produced 761 syntax errors.
2015-03-09 18:50:51,279 | WARN  | ResourceMinificationServiceImpl: Could not minify resources, returned unminified bytes
org.mozilla.javascript.EvaluatorException: Compilation produced 761 syntax errors.
        at org.broadleafcommerce.common.resource.service.ResourceMinificationServiceImpl$1.runtimeError(ResourceMinificationServiceImpl.java:158)
        at org.mozilla.javascript.Parser.parse(Parser.java:392)
        at org.mozilla.javascript.Parser.parse(Parser.java:337)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
        at org.broadleafcommerce.common.resource.service.ResourceMinificationServiceImpl.minify(ResourceMinificationServiceImpl.java:107)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl.createBundle(ResourceBundlingServiceImpl.java:161)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl.getBundle(ResourceBundlingServiceImpl.java:101)
        at org.broadleafcommerce.common.web.resource.BroadleafResourceHttpRequestHandler.getResourceInternal(BroadleafResourceHttpRequestHandler.java:104)
        at org.broadleafcommerce.common.web.resource.BroadleafResourceHttpRequestHandler.getResource(BroadleafResourceHttpRequestHandler.java:98)
        at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:125)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:49)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:335)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:197)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-03-09 18:55:48,273 | WARN  | DataBinder: Skipping URI variable 'id' since the request contains a bind value with the same name.
``

**Comment by phillipuniverse** [comment]
Closing this as this is resolved in #1353.
