### ISSUE TITLE
NPE in CustomerStateFilter on error dispatch

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1306]
In 4.0.0-BETA13, `BroadleafRequestFilter` extends `OncePerRequestFilter`, but `CustomerStateFilter` doesn't. On an error dispatch this means BRF doesn't run but CSF does, resulting in NPE:

    java.lang.NullPointerException: null
	    at org.broadleafcommerce.common.web.BroadleafRequestCustomerResolverImpl.setCustomer(BroadleafRequestCustomerResolverImpl.java:62)
	    at org.broadleafcommerce.profile.web.core.CustomerState.setCustomer(CustomerState.java:57)
	    at org.broadleafcommerce.profile.web.core.security.CustomerStateRequestProcessor.process(CustomerStateRequestProcessor.java:148)
	    at org.broadleafcommerce.profile.web.core.security.CustomerStateFilter.doFilter(CustomerStateFilter.java:55)

I think as long as `CustomerStateFilter` never runs when `BroadleafRequestFilter` hasn't, that would fix this. For my purposes, neither needs to run on an error page, but it's not clear to me that this should be the general behavior else I'd send a pull request.

**Comment by bpolster** [comment]
Thanks for the report Steve.   We are looking into it.

**Comment by ktisdell** [comment]
Should be fixed with this commit: https://github.com/BroadleafCommerce/BroadleafCommerce/commit/534723a52e50da6cc9ee8a9e5655b437d1db6cac
