### ISSUE TITLE
Exception when editing Offer

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1336]
Steps to reproduce (4.0.0-RC1):

1. Create an Offer of type "Order Item" with a target rule.
2. Change type to "Order".
3. Save

Looks like the target rule gets removed from the persistence context but not the offer.

    Caused by: java.lang.IllegalArgumentException: org.hibernate.ObjectDeletedException: deleted instance passed to merge: [org.broadleafcommerce.core.offer.domain.OfferTargetCriteriaXrefImpl#<null>]
        at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:892)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
        at com.sun.proxy.$Proxy178.merge(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
        at com.sun.proxy.$Proxy178.merge(Unknown Source)
        at org.broadleafcommerce.openadmin.server.dao.DynamicEntityDaoImpl.merge(DynamicEntityDaoImpl.java:158)
    at org.broadleafcommerce.openadmin.server.service.persistence.module.BasicPersistenceModule.update(BasicPersistenceModule.java:754)
        ... 163 common frames omitted
        Caused by: org.hibernate.ObjectDeletedException: deleted instance passed to merge: [org.broadleafcommerce.core.offer.domain.OfferTargetCriteriaXrefImpl#<null>]
        at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:189)
        at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:843)
        at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:825)
        at org.hibernate.engine.spi.CascadingAction$6.cascade(CascadingAction.java:288)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:396)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:339)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
        at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:426)
        at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:366)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:342)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:164)
        at org.hibernate.event.internal.DefaultMergeEventListener.cascadeOnMerge(DefaultMergeEventListener.java:468)
        at org.hibernate.event.internal.DefaultMergeEventListener.entityIsPersistent(DefaultMergeEventListener.java:212)
        at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:186)
        at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86)
        at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:833)
        at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:817)
        at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:821)
        at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:889)
        ... 177 common frames omitted

**Comment by jefffischer** [comment]
This issue should be addressed by the commit. Closing in anticipation of this fix making it into RC2 and GA.
