### ISSUE TITLE
Exception in Admin/Change Password

### ISSUE THREAD

**Issue by arunmrao** [BroadleafCommerce/BroadleafCommerce#1337]
Login in admin application (4.0.0-RC1) and click on Change Password on top right throws Exception:
```
java.lang.NullPointerException
 at org.broadleafcommerce.openadmin.web.controller.AdminLoginController.changePassword(AdminLoginController.java:17
 at sun.reflect.GeneratedMethodAccessor2310.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvobleHandlerMethod.java:110)
```

**Comment by bpolster** [comment]
Reproducible in community only in QA.

**Comment by bpolster** [comment]
![screen shot 2015-04-29 at 6 31 21 am](https://cloud.githubusercontent.com/assets/1189191/7390030/626e3050-ee39-11e4-94bc-137899c03427.png)

**Comment by arunmrao** [comment]
Got past it by patching AdminLoginController as follows:
```
    @RequestMapping(value="/changePassword", method=RequestMethod.GET)
    public String changePassword(HttpServletRequest request, HttpServletResponse response, Model model) {
        SecurityContext c = SecurityContextHolder.getContext();
        if (c.getAuthentication()==null) {
        	return "login/notAuthorized";
        }
        else {
	        model.addAttribute("username", ((AdminUserDetails) c.getAuthentication().getPrincipal()).getUsername());
	        return "login/changePasswordPopup";
        }
    }
```

**Comment by pbaggett** [comment]
This is actually a problem in DemoSite, please see BroadleafCommerce/DemoSite#167 and this commit for the fix if you've forked DemoSite: https://github.com/BroadleafCommerce/DemoSite/commit/a7415129794025c08bd44b790aac521509aa1868
