### ISSUE TITLE
multiship address save exception

### ISSUE THREAD

**Issue by ncrum** [BroadleafCommerce/BroadleafCommerce#1340]
To Recreate:
1. choose multiple shipping options
2. on the dropdown choose add new address
3. type in info
4. exception occurs

```
[artifact:mvn] May 04, 2015 2:47:54 PM org.apache.catalina.core.StandardWrapperValve invoke
[artifact:mvn] SEVERE: Servlet.service() for servlet [mycompany] in context with path [] threw exception [Request processing failed; nested exception is javax.persistence.PersistenceException: org.hibernate.PropertyValueException: not-null property references a null or transient value: org.broadleafcommerce.profile.core.domain.PhoneImpl.phoneNumber] with root cause
[artifact:mvn] org.hibernate.PropertyValueException: not-null property references a null or transient value: org.broadleafcommerce.profile.core.domain.PhoneImpl.phoneNumber
[artifact:mvn]  at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:103)
[artifact:mvn]  at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:132)
[artifact:mvn]  at org.hibernate.action.internal.AbstractEntityInsertAction.makeEntityManaged(AbstractEntityInsertAction.java:141)
[artifact:mvn]  at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:209)
[artifact:mvn]  at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:183)
[artifact:mvn]  at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:136)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:329)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:135)
[artifact:mvn]  at org.hibernate.ejb.event.EJB3MergeEventListener.saveWithGeneratedId(EJB3MergeEventListener.java:71)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.saveTransientEntity(DefaultMergeEventListener.java:236)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:216)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:154)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:913)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:895)
[artifact:mvn]  at org.hibernate.engine.spi.CascadingAction$6.cascade(CascadingAction.java:288)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:387)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:330)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:208)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:165)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:424)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:213)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:154)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:913)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:895)
[artifact:mvn]  at org.hibernate.engine.spi.CascadingAction$6.cascade(CascadingAction.java:288)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:387)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:330)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:208)
[artifact:mvn]  at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:165)
[artifact:mvn]  at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:424)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:213)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:154)
[artifact:mvn]  at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:76)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:903)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:887)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:891)
[artifact:mvn]  at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:889)
[artifact:mvn]  at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn]  at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
[artifact:mvn]  at com.sun.proxy.$Proxy128.merge(Unknown Source)
[artifact:mvn]  at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn]  at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
[artifact:mvn]  at com.sun.proxy.$Proxy128.merge(Unknown Source)
[artifact:mvn]  at org.broadleafcommerce.profile.core.dao.CustomerAddressDaoImpl.save(CustomerAddressDaoImpl.java:51)
[artifact:mvn]  at org.broadleafcommerce.profile.core.service.CustomerAddressServiceImpl.saveCustomerAddress(CustomerAddressServiceImpl.java:55)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn]  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
[artifact:mvn]  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
[artifact:mvn]  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
[artifact:mvn]  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
[artifact:mvn]  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
[artifact:mvn]  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
[artifact:mvn]  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
[artifact:mvn]  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
[artifact:mvn]  at com.sun.proxy.$Proxy182.saveCustomerAddress(Unknown Source)
[artifact:mvn]  at org.broadleafcommerce.core.web.controller.checkout.BroadleafShippingInfoController.saveMultishipAddAddress(BroadleafShippingInfoController.java:291)
[artifact:mvn]  at com.mycompany.controller.checkout.ShippingInfoController.saveMultishipAddAddress(ShippingInfoController.java:81)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn]  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
[artifact:mvn]  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
[artifact:mvn]  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
[artifact:mvn]  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
[artifact:mvn]  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
[artifact:mvn]  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
[artifact:mvn]  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
[artifact:mvn]  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
[artifact:mvn]  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
[artifact:mvn]  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
[artifact:mvn]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
[artifact:mvn]  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
[artifact:mvn]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
[artifact:mvn]  at org.broadleafcommerce.cms.web.URLHandlerFilter.doFilterInternal(URLHandlerFilter.java:95)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.core.web.order.security.CartStateFilter.doFilterInternal(CartStateFilter.java:121)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.common.web.filter.TranslationFilter.doFilter(TranslationFilter.java:51)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.profile.web.core.security.CustomerStateFilter.doFilterInternal(CustomerStateFilter.java:57)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.common.web.BroadleafRequestFilter.doFilterInternal(BroadleafRequestFilter.java:104)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:166)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
[artifact:mvn]  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.profile.web.core.security.SessionFixationProtectionFilter.doFilter(SessionFixationProtectionFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.broadleafcommerce.common.security.handler.CsrfFilter.doFilter(CsrfFilter.java:85)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:144)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
[artifact:mvn]  at org.broadleafcommerce.common.web.filter.EstablishSessionFilter.doFilter(EstablishSessionFilter.java:43)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:166)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
[artifact:mvn]  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
[artifact:mvn]  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
[artifact:mvn]  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
[artifact:mvn]  at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:123)
[artifact:mvn]  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
[artifact:mvn]  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
[artifact:mvn]  at org.apache.catalina.core.StandardHostValve.__invoke(StandardHostValve.java:171)
[artifact:mvn]  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
[artifact:mvn]  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
[artifact:mvn]  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
[artifact:mvn]  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
[artifact:mvn]  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
[artifact:mvn]  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
[artifact:mvn]  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
[artifact:mvn]  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
[artifact:mvn]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[artifact:mvn]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[artifact:mvn]  at java.lang.Thread.run(Thread.java:745)
[artifact:mvn]
```

**Comment by ncrum** [comment]
This exception is caused for a few reasons:
1. The init binder was not running when the form was submitted.
2. Even if it had run, it wouldn't have prevented null values and cause an NPE most likely
3. ShippingInfoForm creates PhonePrimary, PhoneSecondary, and PhoneFax PhoneImpl's in it's constructor with null phoneNumber fields. This in turn caused a PropertyValueException during Cascading.

Solution:
* [x] Fix the html to use the init binder correctly
* [x] Fix the init binder to prevent null values by checking for blank input
* [x] Remove the constructor for ShippingInfoForm to prevent unnecessary PhoneFax and PhoneSecondary PhoneImpl's from being created
* [ ] Check history on why constructor was used in the first place to avoid breaking something elsewhere
* [ ] Verify all instance's in which a ShippingInfoForm is used works for DemoSite
* [ ] Verify all instance's in which a ShippingInfoForm is used works for DemoSitePrivate
