### ISSUE TITLE
Oracle deadlock during jobs event processing

### ISSUE THREAD

**Issue by justin-itson** [BroadleafCommerce/BroadleafCommerce#1521]
Tracked under BLS-216

```
2015-07-20 00:02:15,039 ERROR [org.broadleafcommerce.core.util.service.ResourcePurgeServiceImpl][Thread-10600] [ResourcePurgeServiceImpl.java:143] request-id: Unable to purge carts
org.springframework.dao.CannotAcquireLockException: ORA-00060: deadlock detected while waiting for resource
; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: ORA-00060: deadlock detected while waiting for resource

at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:246) ~[spring-orm-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:221) ~[spring-orm-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757) ~[spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726) ~[spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at org.broadleafcommerce.common.util.TransactionUtils.finalizeTransaction(TransactionUtils.java:93) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.endTransaction(StreamingTransactionCapableUtil.java:209) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runOptionalTransactionalOperation(StreamingTransactionCapableUtil.java:147) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runTransactionalOperation(StreamingTransactionCapableUtil.java:113) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runStreamingTransactionalOperation(StreamingTransactionCapableUtil.java:94) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runStreamingTransactionalOperation(StreamingTransactionCapableUtil.java:71) ~[broadleaf-common-4.0.0-PATCH1.jar:na]
at org.broadleafcommerce.core.util.service.ResourcePurgeServiceImpl.purgeCarts(ResourcePurgeServiceImpl.java:117) ~[broadleaf-framework-4.0.0-PATCH1.jar:na]
at com.broadleafcommerce.enterprise.workflow.service.event.PurgeCartSystemEventConsumer.consumeEvent(PurgeCartSystemEventConsumer.java:95) [broadleaf-enterprise-2.0.0-PATCH1.jar:na]
at com.broadleafcommerce.jobsevents.service.DatabaseSystemEventNodeImpl.executeEvent(DatabaseSystemEventNodeImpl.java:717) [broadleaf-jobs-events-1.1.0-PATCH2.jar:na]
at com.broadleafcommerce.jobsevents.service.DatabaseSystemEventNodeImpl$4$1.run(DatabaseSystemEventNodeImpl.java:432) [broadleaf-jobs-events-1.1.0-PATCH2.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
Caused by: org.hibernate.exception.LockAcquisitionException: ORA-00060: deadlock detected while waiting for resource

at org.hibernate.dialect.Oracle8iDialect$2.convert(Oracle8iDialect.java:449) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at com.sun.proxy.$Proxy375.executeUpdate(Unknown Source) ~[na:na]
at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3303) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3506) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:100) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:362) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:354) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:280) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:326) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1213) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:402) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:75) ~[hibernate-entitymanager-4.1.11.Final.jar:4.1.11.Final]
at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517) ~[spring-orm-4.1.6.RELEASE.jar:4.1.6.RELEASE]
... 13 common frames omitted
Caused by: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3665) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1352) ~[ojdbc6-11g-2-11.2.0.3.0.jar:11.2.0.3.0]
at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105) ~[c3p0-0.9.1.1.jar:0.9.1.1]
at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122) ~[hibernate-core-4.1.11.Final.jar:4.1.11.Final]
... 30 common frames omitted
```

**Comment by danielcolgrove** [comment]
Going to move this into our support queue and will work it from there.
