### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/maven/shared/utils/cli/javatool/JavaToolException

### ISSUE THREAD

**Issue by nijogeorgep** [BroadleafCommerce/BroadleafCommerce#1549]
I have followed getting started to setup broadleaf on my machine..while building using maven, i'm getting following error

I'm using java 8, is there any problem with this?
 

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ecommerce
[INFO] core
[INFO] admin
[INFO] site
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ecommerce 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ ecommerce-website ---
[INFO] Installing /home/nijo/MyResources/eclipse-workspace/DemoSite/pom.xml to /home/nijo/.m2/repository/com/ndz/ecommerce-website/1.0/ecommerce-website-1.0.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building core 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.broadleafcommerce:broadleaf-menu:jar:1.0.0-GA is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 86 resources
[INFO] 
[INFO] --- jrebel-maven-plugin:1.1.5:generate (generate-rebel-xml) @ core ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to /home/nijo/MyResources/eclipse-workspace/DemoSite/core/target/classes
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/broadleafcommerce/broadleaf-menu/1.0.0-GA/broadleaf-menu-1.0.0-GA.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/broadleafcommerce/broadleaf-menu/1.0.0-GA/broadleaf-menu-1.0.0-GA.jar; error in opening zip file
[INFO] /home/nijo/MyResources/eclipse-workspace/DemoSite/core/src/main/java/com/ndz/sample/vendor/nullPaymentGateway/web/processor/NullPaymentGatewayHostedActionProcessor.java: /home/nijo/MyResources/eclipse-workspace/DemoSite/core/src/main/java/com/ndz/sample/vendor/nullPaymentGateway/web/processor/NullPaymentGatewayHostedActionProcessor.java uses or overrides a deprecated API.
[INFO] /home/nijo/MyResources/eclipse-workspace/DemoSite/core/src/main/java/com/ndz/sample/vendor/nullPaymentGateway/web/processor/NullPaymentGatewayHostedActionProcessor.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/nijo/MyResources/eclipse-workspace/DemoSite/core/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ core ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ core ---
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ core ---
[INFO] Building jar: /home/nijo/MyResources/eclipse-workspace/DemoSite/core/target/core-1.0.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ core ---
[INFO] Installing /home/nijo/MyResources/eclipse-workspace/DemoSite/core/target/core-1.0.jar to /home/nijo/.m2/repository/com/ndz/core/1.0/core-1.0.jar
[INFO] Installing /home/nijo/MyResources/eclipse-workspace/DemoSite/core/pom.xml to /home/nijo/.m2/repository/com/ndz/core/1.0/core-1.0.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building admin 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.broadleafcommerce:broadleaf-admin-module:jar:4.0.5-GA is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ admin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- build-helper-maven-plugin:1.7:timestamp-property (timestamp-property) @ admin ---
[WARNING] Using platform locale (en_IN actually) to format date/time, i.e. build is platform dependent!
[INFO] Setting property 'clientBuildDate' to '2015-12-17 09:59:02'.
[INFO] 
[INFO] --- keytool-maven-plugin:1.5:clean (clean) @ admin ---
[WARNING] The POM for org.apache.maven:maven-plugin-api:jar:2.1.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.codehaus.mojo:keytool-api:jar:1.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven.shared:maven-shared-utils:jar:0.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven:maven-toolchain:jar:2.1.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.codehaus.mojo:keytool-api-1.7:jar:1.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Keystore file '/home/nijo/MyResources/eclipse-workspace/DemoSite/admin/target/admin/WEB-INF/blc-example.keystore' doesn't exist.
[INFO] 
[INFO] --- keytool-maven-plugin:1.5:generateKeyPair (generateKeyPair) @ admin ---
[WARNING] Error injecting: org.codehaus.mojo.keytool.GenerateKeyPairMojo
java.lang.NoClassDefFoundError: org/apache/maven/shared/utils/cli/javatool/JavaToolException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:658)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:882)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.shared.utils.cli.javatool.JavaToolException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 55 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ecommerce .......................................... SUCCESS [  0.823 s]
[INFO] core ............................................... SUCCESS [  8.686 s]
[INFO] admin .............................................. FAILURE [  0.529 s]
[INFO] site ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.259 s
[INFO] Finished at: 2015-12-17T15:29:02+05:30
[INFO] Final Memory: 30M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.5:generateKeyPair (generateKeyPair) on project admin: Execution generateKeyPair of goal org.codehaus.mojo:keytool-maven-plugin:1.5:generateKeyPair failed: A required class was missing while executing org.codehaus.mojo:keytool-maven-plugin:1.5:generateKeyPair: org/apache/maven/shared/utils/cli/javatool/JavaToolException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/nijo/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
[ERROR] urls[1] = file:/home/nijo/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar
[ERROR] urls[2] = file:/home/nijo/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.5/maven-shared-utils-0.5.jar
[ERROR] urls[3] = file:/home/nijo/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[4] = file:/home/nijo/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar
[ERROR] urls[5] = file:/home/nijo/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.maven.shared.utils.cli.javatool.JavaToolException
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :admin

```

**Comment by cja769** [comment]
I would start by deleting your .m2 directory. If you look toward the top at 
```
ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/broadleafcommerce/broadleaf-menu/1.0.0-GA/broadleaf-menu-1.0.0-GA.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar; error in opening zip file
[ERROR] error reading /home/nijo/.m2/repository/org/broadleafcommerce/broadleaf-menu/1.0.0-GA/broadleaf-menu-1.0.0-GA.jar; error in opening zip file
```
that's where the problem is. It seems like maybe the files are corrupt so deleting your .m2 folder will force maven to re-download the jars.

Java 8 should be fine btw
