### ISSUE TITLE
extends productImpl throw exception 

### ISSUE THREAD

**Issue by coolsunchen** [BroadleafCommerce/BroadleafCommerce#1562]
I use DemoSite-broadleaf-4.0.5-GA version ,I extends ProductImpl according to document,and add relate configurations to persistence.xml and applicationContext.xml;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "MY_PRODUCT")
public class MyProductImpl extends ProductImpl implements Product{
  
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  @Column(name = "MY_CUSTTOM_NAME")
  private String myCustomName;
  
  
  public String getMyCustomName() {
    return myCustomName;
  }
  public void setMyCustomerName(String myCustomName) {
    this.myCustomName = myCustomName;
  }
  
  when i start DemoSite-broadleaf-4.0.5-GA admin, error is :

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in resource loaded from byte array: Cannot resolve reference to bean 'blPersistenceUnitManager' while setting bean property 'persistenceUnitManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blPersistenceUnitManager' defined in resource loaded from byte array: Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.IllegalStateException: The classes
[artifact:mvn] [org.broadleafcommerce.core.catalog.domain.ProductImpl, com.mycompany.sample.integration.MyProductImpl]
[artifact:mvn] are managed classes within the MergePersistenceUnitManager
[artifact:mvn] but were not detected as being transformed by the EntityMarkerClassTransformer. These
[artifact:mvn] classes are likely loaded earlier in the application startup lifecyle by the servlet
[artifact:mvn] container. Verify that an empty <absolute-ordering /> element is contained in your
[artifact:mvn] web.xml to disable scanning for ServletContainerInitializer classes by your servlet
[artifact:mvn] container which can trigger early class loading. If the problem persists, ensure that
[artifact:mvn] there are no bean references to your entity class anywhere else in your Spring applicationContext
[artifact:mvn] and consult the documentation for your servlet container to determine if classes are loaded
[artifact:mvn] prior to the Spring context initialization. Also, it is a necessity that 
[artifact:mvn] '-javaagent:/path/to/spring-instrument-4.1.5.jar' be added to the JVM args of the server.
[artifact:mvn] Finally, ensure that Session Persistence is also disabled by your Servlet Container.
[artifact:mvn] To do this in Tomcat, add <Manager pathname="" /> inside of the <Context> element
[artifact:mvn] in context.xml in your app's META-INF folder or your server's conf folder.
[artifact:mvn] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
[artifact:mvn] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1477)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1222)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
[artifact:mvn] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
[artifact:mvn] 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
[artifact:mvn] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:747)
[artifact:mvn] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
[artifact:mvn] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
[artifact:mvn] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
[artifact:mvn] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
[artifact:mvn] 	at org.broadleafcommerce.common.web.extensibility.MergeContextLoader.contextInitialized(MergeContextLoader.java:148)
[artifact:mvn] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
[artifact:mvn] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
[artifact:mvn] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[artifact:mvn] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
[artifact:mvn] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
[artifact:mvn] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[artifact:mvn] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[artifact:mvn] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[artifact:mvn] 	at java.lang.Thread.run(Thread.java:745)
[artifact:mvn] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blPersistenceUnitManager' defined in resource loaded from byte array: Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.IllegalStateException: The classes
[artifact:mvn] [org.broadleafcommerce.core.catalog.domain.ProductImpl, com.mycompany.sample.integration.MyProductImpl]
[artifact:mvn] are managed classes # **within the MergePersistenceUnitManager
[artifact:mvn] but were not detected as being transformed by the EntityMarkerClassTransformer.** These
[artifact:mvn] classes are likely loaded earlier in the application startup lifecyle by the servlet
[artifact:mvn] container. Verify that an empty <absolute-ordering /> element is contained in your
[artifact:mvn] web.xml to disable scanning for ServletContainerInitializer classes by your servlet
[artifact:mvn] container which can trigger early class loading. If the problem persists, ensure that
[artifact:mvn] there are no bean references to your entity class anywhere else in your Spring applicationContext
[artifact:mvn] and consult the documentation for your servlet container to determine if classes are loaded
[artifact:mvn] prior to the Spring context initialization. Also, it is a necessity that 
[artifact:mvn] '-javaagent:/path/to/spring-instrument-4.1.5.jar' be added to the JVM args of the server.
[artifact:mvn] Finally, ensure that Session Persistence is also disabled by your Servlet Container.
[artifact:mvn] To do this in Tomcat, add <Manager pathname="" /> inside of the <Context> element
[artifact:mvn] in context.xml in your app's META-INF folder or your server's conf folder.
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
[artifact:mvn] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
[artifact:mvn] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
[artifact:mvn] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)

**Comment by coolsunchen** [comment]
<bean id="org.broadleafcommerce.core.catalog.domain.Product" class="com.mycompany.sample.integration.MyProductImpl" scope="prototype">
	    </bean>
should put in  applicationContext-entity.xml,not applicationContext.xml
