### ISSUE TITLE
CMS - Displaying static asset does not work

### ISSUE THREAD

**Issue by linuxidefix** [BroadleafCommerce/BroadleafCommerce#1585]
# Blc version 5.1/5.2
1) Start demo or community starter demo ( front or admin )
Display a static asset.

# Quick how to reproduce
```
# Community starter
docker run --rm -ti  -p 18081:8081 linuxidefix/communitystarter
cd admin;
mvn spring-boot:run
```
Go to http://localhost:18081/admin/cmsstatic/img/banners/shirt-special.jpg

2) Log
``
Caused by: java.io.FileNotFoundException: /tmp/5e/7c/shirt-special.jpg (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_111]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_111]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_111]
	at org.broadleafcommerce.cms.file.service.StaticAssetStorageServiceImpl.lookupAssetAndCreateLocalFile(StaticAssetStorageServiceImpl.java:132) ~[broadleaf-contentmanagement-module-5.2.0-SNAPSHOT.jar:na]
	at org.broadleafcommerce.cms.file.service.StaticAssetStorageServiceImpl.getCacheFileModel(StaticAssetStorageServiceImpl.java:231) ~[broadleaf-contentmanagement-module-5.2.0-SNAPSHOT.jar:na]
	at org.broadleafcommerce.cms.file.service.StaticAssetStorageServiceImpl$$FastClassBySpringCGLIB$$7f026353.invoke(<generated>) ~[broadleaf-contentmanagement-module-5.2.0-SNAPSHOT.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.broadleafcommerce.cms.file.service.StaticAssetStorageServiceImpl$$EnhancerBySpringCGLIB$$3aa3d42c.getCacheFileModel(<generated>) ~[broadleaf-contentmanagement-module-5.2.0-SNAPSHOT.jar:na]
	at org.broadleafcommerce.cms.web.file.StaticAssetViewController.handleRequestInternal(StaticAssetViewController.java:138) ~[broadleaf-contentmanagement-module-5.2.0-SNAPSHOT.jar:na]
	... 62 common frames omitted
``
![asset-bug](https://cloud.githubusercontent.com/assets/836182/25273822/cc61e95a-268d-11e7-9c11-6782a566c7b6.png)

What I understood:
- a hash is generated from the file's name (url)
- a new filename is created based on that hash (/xx/yy/filename.jpg)
- file is never created, so code fails when trying to copy it.

# org.broadleafcommerce.common.file.service.FileSystemFileServiceProvider#buildResourceName
The method's comment says "Stores the file on the file-system " but is does not ( and it should not in my opinion.)

Maybe is should de done there
# org.broadleafcommerce.common.file.service.FileSystemFileServiceProvider#getResource(java.lang.String, org.broadleafcommerce.common.file.service.type.FileApplicationType)
- by calling org.broadleafcommerce.common.file.service.FileSystemFileServiceProvider#addOrUpdateResourcesForPaths to create the file in the write path ?
- or using an _BroadleafFileServiceExtensionHandler_?

**Comment by linuxidefix** [comment]
In fact this is more a site/admin webapp problem that a framework problem.
( maybe issue maybe moved/linked to an issue in CommunittyStarter and Demosite.  )

![screenshot-localhost 8081-2017-04-24-5-49-12](https://cloud.githubusercontent.com/assets/836182/25345942/88f8d2f6-2916-11e7-9f27-8a7157d2916a.png)

/img/workflow.png
/img/pricing.png
/img/offers-and-promotions.png
/img/content-targeting.png
/img/banners/shirts-speciale.jpg
/img/banners/shirt-special.jpg
/img/banners/promocion-camisas.jpg
/img/banners/member-special.jpg
/img/banners/buy-two-get-one.jpg
/img/banners/buy-one-get-one-home-banner.jpg

These resources are missing or are not found in the classpath under a directory named /cms/static/ 
see org.broadleafcommerce.common.file.service.BroadleafFileServiceImpl#lookupResourceOnClassPath
(asset.server.file.classpath.directory=cms/static)

2 solutions: 
A: 
remove these lines from sql demo dataset

B:
- move or create the files in core/src/main/resources/cms/static/
- remove all jpg images from  banners folder in front except  /img/banners/shirt-special.jpg ( only file directly used in html template)
