### ISSUE TITLE
Translation Service problem in recent 5.2.1-SNAPSHOT build

### ISSUE THREAD

**Issue by droyop** [BroadleafCommerce/BroadleafCommerce#1684]
There is a problem which has suddenly appeared in one of the latest 5.2.1 snapshot builds. I tried anything to make my project work again to no avail.

I reverted the Broadleaf version to 5.2.0-SNAPSHOT instead of 5.2.1-SNAPSHOT and it works fine again

Commit [3a88716a0cf15c9ef626453edffe7d9fed93053a](https://github.com/BroadleafCommerce/BroadleafCommerce/commit/3a88716a0cf15c9ef626453edffe7d9fed93053a) looks suspicious but it's just a wild guess

```
2017-09-06 23:05:45.957 ERROR 21544 --- [nio-8443-exec-8] org.thymeleaf.TemplateEngine             : [THYMELEAF][https-jsse-nio-8443-exec-8] Exception processing template "catalog/category": Error during execution of processor 'org.broadleafcommerce.presentation.thymeleaf3.dialect.DelegatingThymeleaf3VariableModifierProcessor' (template: "layout/partials/nav" - line 8, col 5)

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.broadleafcommerce.presentation.thymeleaf3.dialect.DelegatingThymeleaf3VariableModifierProcessor' (template: "layout/partials/nav" - line 8, col 5)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:111) ~[thymeleaf-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.0.7.RELEASE.jar:3.0.7.RELEASE]

```

```
Caused by: java.lang.IllegalArgumentException: TranslatedEntity type was not set to a known class
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl.getEntityType(TranslationServiceImpl.java:374) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl.getEntityType(TranslationServiceImpl.java:381) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl.getTranslatedValue(TranslationServiceImpl.java:172) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl$$FastClassBySpringCGLIB$$f73424a7.invoke(<generated>) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl$$EnhancerBySpringCGLIB$$2c868aa4.getTranslatedValue(<generated>) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.common.i18n.service.DynamicTranslationProvider.getValue(DynamicTranslationProvider.java:47) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.menu.domain.MenuItemImpl.getLabel(MenuItemImpl.java:186) ~[broadleaf-menu-2.2.1-SNAPSHOT.jar:na]
	at org.broadleafcommerce.menu.domain.MenuItemImpl.getDerivedLabel(MenuItemImpl.java:288) ~[broadleaf-menu-2.2.1-SNAPSHOT.jar:na]
```
```
Caused by: java.lang.ClassNotFoundException: com.broadleafcommerce.theme.domain.ThemeDefinition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152-release]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152-release]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_152-release]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152-release]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_152-release]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_152-release]
	at org.broadleafcommerce.common.i18n.service.TranslationServiceImpl.getEntityType(TranslationServiceImpl.java:369) ~[broadleaf-common-5.2.1-SNAPSHOT.jar:na]
```

**Comment by phillipuniverse** [comment]
@nathandmoore is this fixed?

**Comment by phillipuniverse** [comment]
If so, go ahead and close.

**Comment by droyop** [comment]
Fixed for me! 

Thanks a lot

**Comment by phillipuniverse** [comment]
👍
