### ISSUE TITLE
admin installation error in broadleaf .. please give the sollution for this

### ISSUE THREAD

**Issue by santoshraju621** [BroadleafCommerce/BroadleafCommerce#1685]
65357K of 142888K >>  65439K of 142888K >>  65521K of 142888K >>  2017-09-07 17:11:23.527 ERROR 8960 --- [           main] c.b.solr.autoconfigure.SolrServer        : Unable to download solr. If you need to connect through a proxy, the 'solr.dowload.proxyHost', 'solr.download.proxyPort', 'solr.download.proxyUserName' and 'solr.download.proxyPassword' properties are available. Also, make sure the user running this application has write priveleges to the download directory C:\Users\USER\AppData\Local\Temp\solr-5.3.1. A different download directory may be specified via the 'solr.server.workingDirectory' property.

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170) ~[commons-httpclient-3.1.jar:na]
	at java.io.FilterInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:108) ~[commons-httpclient-3.1.jar:na]
	at java.io.BufferedInputStream.fill(Unknown Source) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at java.io.FilterInputStream.read(Unknown Source) ~[na:1.8.0_144]
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.copyLarge(SolrServer.java:433) [broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.downloadSolrIfApplicable(SolrServer.java:318) [broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.startSolr(SolrServer.java:133) [broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.start(SolrServer.java:96) [broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:546) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.community.admin.AdminApplication.main(AdminApplication.java:18) [classes/:na]

2017-09-07 17:11:23.530  WARN 8960 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'blAutoSolrServer'; nested exception is java.lang.IllegalStateException: Could not download or expand Solr, see previous logs for more information
2017-09-07 17:11:23.558  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans on shutdown
2017-09-07 17:11:23.558  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans
2017-09-07 17:11:23.565  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans on shutdown
2017-09-07 17:11:23.565  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans
2017-09-07 17:11:23.622  INFO 8960 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'blPU'
2017-09-07 17:11:23.623  INFO 8960 --- [           main] o.b.c.c.e.AbstractHydratedCacheManager   : Disposing of all hydrated cache members
2017-09-07 17:11:23.632  INFO 8960 --- [           main] o.b.c.c.e.AbstractHydratedCacheManager   : Disposing of all hydrated cache members
2017-09-07 17:11:23.645  INFO 8960 --- [           main] o.b.c.c.e.AbstractHydratedCacheManager   : Disposing of all hydrated cache members
2017-09-07 17:11:23.653  INFO 8960 --- [           main] o.b.c.c.e.AbstractHydratedCacheManager   : Disposing of all hydrated cache members
2017-09-07 17:11:23.704  INFO 8960 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'blCMSStorage'
2017-09-07 17:11:23.734  INFO 8960 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'blSecurePU'
2017-09-07 17:11:23.735  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans on shutdown
2017-09-07 17:11:23.735  INFO 8960 --- [           main] o.s.jmx.export.MBeanExporter             : Unregistering JMX-exposed beans
2017-09-07 17:11:23.769  INFO 8960 --- [           main] b.c.e.c.e.MergeEhCacheManagerFactoryBean : Shutting down EhCache CacheManager
2017-09-07 17:11:23.780  INFO 8960 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-09-07 17:11:23.829  WARN 8960 --- [ost-startStop-2] o.a.c.loader.WebappClassLoaderBase       : The web application [admin] appears to have started a thread named [HSQLDB Server @42912ebc] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
 java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
 java.net.AbstractPlainSocketImpl.accept(Unknown Source)
 java.net.PlainSocketImpl.accept(Unknown Source)
 java.net.ServerSocket.implAccept(Unknown Source)
 java.net.ServerSocket.accept(Unknown Source)
 org.hsqldb.server.Server.run(Unknown Source)
 org.hsqldb.server.Server.access$000(Unknown Source)
 org.hsqldb.server.Server$ServerThread.run(Unknown Source)
2017-09-07 17:11:23.830  WARN 8960 --- [ost-startStop-2] o.a.c.loader.WebappClassLoaderBase       : The web application [admin] appears to have started a thread named [HSQLDB Timer @6e9cfff6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.hsqldb.lib.HsqlTimer$TaskQueue.park(Unknown Source)
 org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
 org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
 java.lang.Thread.run(Unknown Source)
2017-09-07 17:11:23.874  INFO 8960 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-09-07 17:11:23.883 ERROR 8960 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'blAutoSolrServer'; nested exception is java.lang.IllegalStateException: Could not download or expand Solr, see previous logs for more information
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.community.admin.AdminApplication.main(AdminApplication.java:18) [classes/:na]
Caused by: java.lang.IllegalStateException: Could not download or expand Solr, see previous logs for more information
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.startSolr(SolrServer.java:134) ~[broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at com.broadleafcommerce.solr.autoconfigure.SolrServer.start(SolrServer.java:96) ~[broadleaf-boot-starter-solr-1.0.0-GA.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 16 common frames omitted

**Comment by danielcolgrove** [comment]
In the demo application the broadleaf-boot-starter-solr is configured as a dependency in both the site and the admin.  The solr starter will download solr using one of the two urls below.  If the download site is down or there is a transmission issue (proxy or otherwise), then you will get this error.

If the download fails, this is an environment issue that you will need to troubleshoot.

For Windows:
http://archive.apache.org/dist/lucene/solr/5.3.1/solr-5.3.1.zip

For Unix:
http://archive.apache.org/dist/lucene/solr/5.3.1/solr-5.3.1.tgz

**Comment by santoshraju621** [comment]
thanks for the sollution

**Comment by PrabakaranSK** [comment]
There's a typo in source code for below property:
'solr.dowload.proxyHost'

It should be 'solr.download.proxyHost'.
