### ISSUE TITLE
Exception starting filter deploying API in Tomcat

### ISSUE THREAD

**Issue by droyop** [BroadleafCommerce/BroadleafCommerce#1769]
Hi,

I have a problem trying to deploy the API to a google cloud VM. 
I deployed the site successfully and it's working just fine. I deployed api.war alongside with the site (ROOT.war). It fails. I tried deploying api.war renamed as ROOT.war, just in case there was something wrong with the contextPath, but I got the same error. See traces below.

I think [this](https://stackoverflow.com/questions/45649596/broaleaf-5-2-root-war-issue-with-filters) is a really similar issue, if not the same, but I fear I don't have the skills to solve this mistery myself :-)

Is it a code problem or a configuration problem?

In catalina.out...

```
...
Hibernate: select systemprop0_.BLC_SYSTEM_PROPERTY_ID as BLC1_174_, systemprop0_.FRIENDLY_GROUP as FRIENDLY2_174_, systemprop0_.FRIENDLY_NAME as FRIENDLY3_174_, systemprop0_.FRIENDLY_TAB as FRIENDLY4_174_, systemprop0_.PROPERTY_NAME as PROPERTY5_174_, systemprop0_.OVERRIDE_GENERATED_PROP_NAME as OVERRIDE6_174_, systemprop0_.PROPERTY_TYPE as PROPERTY7_174_, systemprop0_.PROPERTY_VALUE as PROPERTY8_174_ from BLC_SYSTEM_PROPERTY systemprop0_ where systemprop0_.PROPERTY_NAME=?
2018-01-11 15:09:29.978  INFO 15930 --- [ost-startStop-1] com.community.api.ApiApplication         : Started ApiApplication in 92.889 seconds (JVM running for 108.512)
11-Jan-2018 15:09:30.140 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file

```
In localhost.log

```
12-Jan-2018 08:57:34.522 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
12-Jan-2018 08:57:53.715 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
12-Jan-2018 08:58:52.765 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter apiCustomerStateFilter
 javax.naming.NameNotFoundException: Name [blCustomerService] is not bound in this Context. Unable to find [blCustomerService].
        at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
        at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:552)
        at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:452)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:134)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

12-Jan-2018 08:58:52.779 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter blSessionFixationProtectionFilter
 javax.naming.NameNotFoundException: Name [blSessionFixationEncryptionModule] is not bound in this Context. Unable to find [blSessionFixationEncryptionModule].
        at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
        at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:552)
        at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:452)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:134)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by phillipuniverse** [comment]
This was resolved in #1771 and is available in 5.2.3-GA.
