### ISSUE TITLE
broadleaf sku.set setProductOptionValueXrefs error

### ISSUE THREAD

**Issue by RichsJeson** [BroadleafCommerce/BroadleafCommerce#2099]
code example:
`
     
        public static Sku addSku(@Nullable SkuEntity pEntity, @Nullable CatalogService pService) {
                Product product = pService.findProductById(pEntity.getProductId());
                if (product == null) {
                    throw BristuaWebServicesException.build(HttpStatus.SC_NOT_FOUND)
                            .addMessage(BristuaWebServicesException.PRODUCT_NOT_FOUND);
                }
                //2 加入sku
                Sku sku = pService.createSku();
                if (!DataUtils.checkNull(pEntity.getDescription())) {
                    sku.setDescription(pEntity.getDescription());
                }
                //验证名称是否存在，存在了就要抛异常给底层
                List<Product> products = pService.findProductsByName(sku.getName());
                if (!DataUtils.checkIsEmpty(products)) {
                    throw build(500);
                }
                if (!DataUtils.checkNull(pEntity.getName())) {
                    sku.setName(pEntity.getName());
                }
                if (!DataUtils.checkNull(pEntity.getDetails())) {
                    sku.setLongDescription(pEntity.getDetails());
                }
                //设置零售价格
                sku.setRetailPrice(new Money(new BigDecimal(pEntity.getRetailPrice())));
                //设置销售价格
                sku.setSalePrice(new Money(new BigDecimal(pEntity.getSalePrice())));
                //默认上架周期
                sku.setActiveStartDate(new Date());
                sku.setActiveEndDate(new Date());
                //设置产品属性
                sku.setDefaultProduct(product);
                sku.setProduct(product);
                //库存属性 字段没地方放，系统认定sku为系统的一组数据，所谓的库存 应该是这组数据的结合体。
                Map<String, String> medias = pEntity.getMedias();
                if (!DataUtils.checkIsMapEmpty(medias)) {
                    //此处可能需要迭代器，进行操作了
                    Map<String, SkuMediaXref> mediaXrefMap = sku.getSkuMediaXref();
                    Iterator<Map.Entry<String, String>> var3 = medias.entrySet().iterator();
                    while (var3.hasNext()) {
                        Map.Entry<String, String> entity = var3.next();
                        Media media = new MediaImpl();
                        media.setAltText(entity.getKey());
                        media.setTitle(entity.getKey());
                        media.setUrl(entity.getValue());
                        mediaXrefMap.put(entity.getKey(), new SkuMediaXrefImpl(sku, media, (entity.getKey())));
                    }
                    sku.setSkuMediaXref(mediaXrefMap);
                }
                //新增自定义属性
                Map<String, String> attributes = pEntity.getAttributes();
                if (!DataUtils.checkIsMapEmpty(attributes)) {
                    //此处可能需要迭代器，进行操作了
                    Map<String, SkuAttribute> skuAttributeMap = new HashedMap();
                    Iterator<Map.Entry<String, String>> var3 = attributes.entrySet().iterator();
                    while (var3.hasNext()) {
                        Map.Entry<String, String> entity = var3.next();
                        SkuAttribute skuAttr = new SkuAttributeImpl();
                        skuAttr.setSku(sku);
                        skuAttr.setValue(entity.getValue());
                        skuAttr.setName(entity.getKey());
                        skuAttributeMap.put(entity.getKey(), skuAttr);
                    }
                    sku.setSkuAttributes(skuAttributeMap);
                }
            List<ProductOption> list = product.getProductOptions();
            List productList = new ArrayList(list);
            productList.add(productOption);
            //先获取下这个列表 好吧，看下是否存在，应为他的对象是存在的；
            sku.getProductOptionValues().clear();
            sku.setProductOptionValueXrefs(sets);

                List<ProductOptionValue> values=sku.getProductOptionValues();
                ProductOption productOption = new ProductOptionImpl();
            productOption.setAttributeName("hellonis demoss");
            productOption.setAllowedValues(valueList);

                //1.保证产品能插入基础属性值

                List<ProductOptionXref> list=product.getProductOptionXrefs();

                ProductOption productOption = new ProductOptionImpl();
                productOption.setAttributeName("hels");
                ProductOptionValue productOptionValue = new ProductOptionValueImpl();
                productOptionValue.setAttributeValue("cc");
                Set<ProductOptionValue> valueList=new HashSet<>();
                valueList.add(productOptionValue);
        //        productOption.setAllowedValues(valueList);
        //        productOptionValue.setProductOption(productOption);
                //这样就说明了，productOpertionValue有值的时候，进行去重，避免名称重复
                if(!list.contains(productOptionValue)) {
                    productOption = pService.saveProductOption(productOption);
                }
                //保存了productOptionValue是吧
                //todo zyb  productOptionValue去重判断
                //1.好了,productOption有了 现在就要考虑对应的关系链了
                //2.是吧，那加入关系链吧
                List<ProductOptionXref> productOptionXrefs=new ArrayList<>(list);

                ProductOptionXref productOptionXref=new ProductOptionXrefImpl();
                productOptionXref.setProductOption(productOption);
                productOptionXref.setProduct(product);

                productOptionXrefs.add(productOptionXref);

                product.setProductOptionXrefs(productOptionXrefs);

                product=pService.saveProduct(product);

                //通过搜索获取productOpetionValue
                List<ProductOptionXref> xref=product.getProductOptionXrefs();
                ProductOption productOption1=xref.get(0).getProductOption();
                List<ProductOptionValue> optionValues=productOption1.getAllowedValues();

                try {
        //            Sku sku1=pService.saveSku(sku);

        //            Sku skus=product.getDefaultSku();
        //            skuXref.setSku(skus);
                    //意思是此处的productOpetionvalue必须要从product中获取，不能随意写死的操作
        //        skuXref.setProductOptionValue(productOptionValue);

        //        ProductOptionValue productOptionValues1= productOptionXrefs.get();
        //        skuXref.setProductOptionValue(productOptionValues1);
        //        skuXref.setSku(sku);
        //
        //            Set<SkuProductOptionValueXref> set=sku1.getProductOptionValueXrefs();
        //            Set<SkuProductOptionValueXref> sets=new HashSet<>(set);
        //
        //

        //            Sku skus=pService.findSkuById(112L);

                    SkuProductOptionValueXref skuXref=new SkuProductOptionValueXrefImpl();
                    skuXref.setProductOptionValue(optionValues.get(0));
                    skuXref.setSku(sku);
        //
                    Set<SkuProductOptionValueXref> xrefSet=new HashSet<>();

                    xrefSet.add(skuXref);
        //
        ////
        //            skus.setProductOptionValuesCollection(valueList);
                    sku.setProductOptionValueXrefs(xrefSet);
        //            skus.setProductOptionValues(optionValues);
                    pService.saveSku(sku);
                }catch (Exception e){
                    e.printStackTrace();
                }
                return null;
            }
`
error:
`
     
                    2019-04-28 11:36:22.078 ERROR 1967 --- [nio-8082-exec-3] o.h.i.ExceptionMapperStandardImpl        : HHH000346: Error during managed flush [null]
                    org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
                        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:545)
                        at org.broadleafcommerce.common.persistence.transaction.LifecycleAwareJpaTransactionManager.doCommit(LifecycleAwareJpaTransactionManager.java:78)
                        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
                        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
                        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:532)
                        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)
                        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
                        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
                        at org.broadleafcommerce.core.catalog.service.CatalogServiceImpl$$EnhancerBySpringCGLIB$$e141822f.saveSku(<generated>)
                        at org.broadleafcommerce.rest.api.business.SkuBusinessHelper.addSku(SkuBusinessHelper.java:219)
                        at org.broadleafcommerce.rest.api.endpoint.SkuEndpoint.addSku(SkuEndpoint.java:134)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
                        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
                        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
                        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
                        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
                        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
                        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
                        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
                        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
                        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
                        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.profile.web.site.security.SessionFixationProtectionFilter.doFilter(SessionFixationProtectionFilter.java:108)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.core.web.geolocation.GeolocationFilter.doFilterInternalUnlessIgnored(GeolocationFilter.java:48)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.core.web.order.security.CartStateFilter.doFilterInternalUnlessIgnored(CartStateFilter.java:127)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.cms.web.URLHandlerFilter.doFilterInternalUnlessIgnored(URLHandlerFilter.java:101)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.common.web.filter.TranslationFilter.doFilterUnlessIgnored(TranslationFilter.java:53)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableFilter.doFilter(AbstractIgnorableFilter.java:60)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.common.web.filter.EntityManagerFindValidationFilter.doFilterInternal(EntityManagerFindValidationFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.profile.web.site.security.CustomerStateFilter.doFilterInternalUnlessIgnored(CustomerStateFilter.java:60)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.core.web.device.BroadleafDeviceResolverRequestFilter.doFilterInternal(BroadleafDeviceResolverRequestFilter.java:67)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.profile.web.core.security.RestApiCustomerStateFilter.doFilter(RestApiCustomerStateFilter.java:125)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
                        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
                        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
                        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.site.common.web.filter.EstablishSessionFilter.doFilterUnlessIgnored(EstablishSessionFilter.java:45)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableFilter.doFilter(AbstractIgnorableFilter.java:60)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.common.web.BroadleafRequestFilter.doFilterInternalUnlessIgnored(BroadleafRequestFilter.java:110)
                        at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:185)
                        at org.broadleafcommerce.common.web.filter.IgnorableOpenEntityManagerInViewFilter.doFilterInternal(IgnorableOpenEntityManagerInViewFilter.java:54)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.broadleafcommerce.common.web.filter.SecurityBasedIgnoreFilter.doFilter(SecurityBasedIgnoreFilter.java:77)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
                        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
                        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
                        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
                        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                        at java.lang.Thread.run(Thread.java:748)
                    Caused by: javax.persistence.RollbackException: Error while committing the transaction
                        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:77)
                        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:71)
                        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:536)
                        ... 134 more
                    Caused by: java.util.ConcurrentModificationException
                        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
                        at java.util.ArrayList$Itr.next(ArrayList.java:859)
                        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
                        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:598)
                        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:474)
                        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
                        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
                        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1437)
                        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:494)
                        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3245)
                        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2451)
                        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
                        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:156)
                        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
                        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
                        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
                        ... 135 more

`

**Comment by StanislavFedorov** [comment]
Hello, RichsJeson.

Could you specify where exactly this error happend?
I saw in your example several setProductOptionValueXrefs.

I have ran this fragment of your code and it worked fine for me.
Could you try it?

	public Sku addSku() {
		Product product = catalogService.findProductById(300L);

		Sku sku = catalogService.createSku();

		List<ProductOptionXref> xref = product.getProductOptionXrefs();
		ProductOption productOption1 = xref.get(0).getProductOption();
		List<ProductOptionValue> optionValues = productOption1.getAllowedValues();


		try {
			SkuProductOptionValueXref skuXref = new SkuProductOptionValueXrefImpl();
			skuXref.setProductOptionValue(optionValues.get(0));
			skuXref.setSku(sku);

			Set<SkuProductOptionValueXref> xrefSet = new HashSet<>();

			xrefSet.add(skuXref);
			sku.setProductOptionValueXrefs(xrefSet);

			catalogService.saveSku(sku);
		}catch (Exception e){
			e.printStackTrace();
		}
		return sku;
	}
