### ISSUE TITLE
NullPointerException in BroadleafThemeProcessor when running site module 

### ISSUE THREAD

**Issue by frostyandy2k** [BroadleafCommerce/BroadleafCommerce#2180]
**Reproduce:**
```
https://github.com/BroadleafCommerce/DemoSite.git
cd DemoSite
git checkout tags/broadleaf-6.0.6-GA
mvn clean install
cd site/ && mvn spring-boot:run # navigate to the URL eg. `localhost:8080`
```

**Resulting Exception:**

```
2019-10-16 17:52:35.751 ERROR 19125 --- [nio-8443-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.NullPointerException: null
	at org.broadleafcommerce.common.web.BroadleafThemeProcessor.process(BroadleafThemeProcessor.java:55) ~[broadleaf-common-6.0.6-GA.jar:na]
	at org.broadleafcommerce.common.web.BroadleafThemeResolverFilter.doFilterInternalUnlessIgnored(BroadleafThemeResolverFilter.java:96) ~[broadleaf-common-6.0.6-GA.jar:na]
	at org.broadleafcommerce.common.web.filter.AbstractIgnorableOncePerRequestFilter.doFilterInternal(AbstractIgnorableOncePerRequestFilter.java:58) ~[broadleaf-common-6.0.6-GA.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]

...

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

2019-10-16 17:50:35.355  INFO 19125 --- [io-8443-exec-10] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.

```

**My Analysis:**

The reason the site crashes is [a comparison on the ID of a Null Object](https://github.com/BroadleafCommerce/BroadleafCommerce/blame/f2361835349b9ef2426d9c258b540f5613031d2e/common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java#L55) introduced as part of some optimization task.

This comes from the [uninitialized Long object in ThemeDTO](https://github.com/BroadleafCommerce/BroadleafCommerce/blame/f2361835349b9ef2426d9c258b540f5613031d2e/common/src/main/java/org/broadleafcommerce/common/site/domain/ThemeDTO.java#L28).

I guess this happens when running the project without any custom configuration of the Theme.
Some more info [here](http://forum.broadleafcommerce.org/viewtopic.php?t=1559).

**Comment by frostyandy2k** [comment]
Added pull request https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2181, but it should be reviewed by the maintainers please.

**Comment by frostyandy2k** [comment]
Is being handled in 6.0.7-GA with https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2183
